export const FETCH_FEED_REQUEST = 'FETCH_FEED_REQUEST';
export const FETCH_FEED_SUCCESS = 'FETCH_FEED_SUCCESS';
export const FETCH_FEED_FAILURE = 'FETCH_FEED_FAILURE';
export const FETCH_OLDER_FEED_REQUEST = 'FETCH_OLDER_FEED_REQUEST';
export const FETCH_OLDER_FEED_SUCCESS = 'FETCH_OLDER_FEED_SUCCESS';
export const FETCH_OLDER_FEED_FAILURE = 'FETCH_OLDER_FEED_FAILURE';
